name: Continuous integration unit testing and lint

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.8', '3.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest QIIME 2 Environment
        shell: bash
        run: |
          wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py38-linux-conda.yml

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: qiime2
          environment-file: qiime2-latest-py38-linux-conda.yml
          auto-activate-base: false

      - name: Install and run unit tests
        run: |
          conda install pytest
          which python
          pip install -e . --no-deps
          pytest

      - name: Lint with flake8
        run: |
          conda activate qiime2
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
